CREATE TABLE IF NOT EXISTS public.classification (
    classification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    classification_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
)